talmolab/sleap-nn

- sleap_nn/data/instance_centroids.py
- sleap_nn/data/providers.py
- tests/test_instance_centroids.py
- tests/test_providers.py
Finds centroid of instance -> #3
> Add centroid finder block

- sleap_nn/data/augmentation.py
- sleap_nn/data/confidence_maps.py
- sleap_nn/data/edge_maps.py
- sleap_nn/data/instance_centroids.py
- sleap_nn/data/instance_cropping.py
- sleap_nn/data/normalization.py
- sleap_nn/data/providers.py
- sleap_nn/data/resizing.py
- sleap_nn/inference/predictors.py
- sleap_nn/inference/topdown.py
- tests/data/test_augmentation.py
- tests/data/test_confmaps.py
- tests/data/test_edge_maps.py
- tests/data/test_instance_centroids.py
- tests/data/test_instance_cropping.py
- tests/data/test_normalization.py
- tests/data/test_providers.py
- tests/data/test_resizing.py
This is the first PR for #80. Here, we breakdown the operations in `__iter__()`  of all data processing modules into individual functions that would be useful for implementing the `get_chunks()` (second PR for #80 ).
> LitData Refactor PR1: Get individual functions for data pipelines

- docs/config.md
- docs/config_bottomup.yaml
- docs/config_centroid.yaml
- docs/config_topdown_centered_instance.yaml
- sleap_nn/data/providers.py
- sleap_nn/data/streaming_datasets.py
- sleap_nn/training/model_trainer.py
- tests/data/test_instance_cropping.py
- tests/data/test_providers.py
- tests/data/test_streaming_datasets.py
- tests/fixtures/datasets.py
- tests/training/test_model_trainer.py
This is the fourth PR for https://github.com/talmolab/sleap-nn/issues/80. Here, we integrate litdata with training.model_trainer.ModelTrainer class. In [_create_data_loaders()](https://github.com/talmolab/sleap-nn/blob/2f44d2db707496e7f2b9f587d69a791f89992bb3/sleap_nn/training/model_trainer.py#L80), ld.optimize(fn = get_chunks) is used to generate the .bin files. The .bin dir path is passed to the litdata.StreamingDataset class. (the .bin files are deleted after training)
> LitData Refactor PR4: Integrate LitData with ModelTrainer class

- docs/config.md
- docs/config_bottomup.yaml
- docs/config_centroid.yaml
- docs/config_topdown_centered_instance.yaml
- environment.yml
- environment_cpu.yml
- environment_mac.yml
- sleap_nn/data/providers.py
- sleap_nn/data/streaming_datasets.py
- sleap_nn/training/model_trainer.py
- tests/data/test_instance_cropping.py
- tests/data/test_providers.py
- tests/data/test_streaming_datasets.py
- tests/fixtures/datasets.py
- tests/training/test_model_trainer.py
This is the third PR for https://github.com/talmolab/sleap-nn/issues/80. Here, we implement a custom `litdata.StreamingDataset` class for each model type. In the `litdata.StreamingDataset.__getitem__()` method, we apply augmentation, resizer, pad_to_stride and generate confidence maps (and part affinity fields for bottom-up model) .
> LitData Refactor PR3: Add custom StreamingDataset

- docs/config.md
- docs/config_bottomup.yaml
- docs/config_centroid.yaml
- docs/config_topdown_centered_instance.yaml
- environment.yml
- environment_cpu.yml
- environment_mac.yml
- sleap_nn/data/get_data_chunks.py
- sleap_nn/data/providers.py
- sleap_nn/data/streaming_datasets.py
- sleap_nn/training/model_trainer.py
- tests/data/test_get_data_chunks.py
- tests/data/test_instance_cropping.py
- tests/data/test_providers.py
- tests/data/test_streaming_datasets.py
- tests/fixtures/datasets.py
- tests/training/test_model_trainer.py
This is the second PR for https://github.com/talmolab/sleap-nn/issues/80. Here, we implement the get_chunks() method for each model pipeline. This method handles all the data preprocessing functions (except augmentation, resizing, padding to stride and confidence map (or pafs) generation) to extract dictionaries from .slp file and save them as .bin files.
> LitData Refactor PR2: Implement a function to get the data chunks for all model types

- sleap_nn/architectures/model.py
- sleap_nn/data/get_data_chunks.py
- sleap_nn/data/providers.py
- sleap_nn/data/resizing.py
- sleap_nn/training/get_bin_files.py
- sleap_nn/training/model_trainer.py
- tests/data/test_get_data_chunks.py
- tests/data/test_resizing.py
- tests/data/test_streaming_datasets.py
This PR adds the functionality to compute the maximum height and width of images across the labels file based on which the images are padded to ensure the image shapes are consistent across the dataset. Previously, users were required to provide the max height and width in the config (`data_config.preprocessing`). If these fields are `None`, then the images wouldn't be padded even if the dimensions were inconsistent.
With this PR, if the `max_height` and `max_width` provided by the user in the config are `None`, the data pipeline computes these automatically from the labels file, which are then used for padding. If values are explicitly set in the config, the user-defined values will take precedence over the computed ones.
> Auto compute max height and width from labels

- sleap_nn/inference/predictors.py
- sleap_nn/training/model_trainer.py
- tests/inference/test_predictors.py
This PR adds an option to load different checkpoints for head and backbone layers while running inference. 
**Note**: Currently, this is possible only when the head layer has different output channels, while all other backbone and head parameters (like output stride) should be the same.
> Add option to load ckpts for backbone and head for running inference

- sleap_nn/data/get_data_chunks.py
- sleap_nn/data/streaming_datasets.py
- tests/inference/test_predictors.py
Currently, in `streaming_datasets.py`, we read the PIL images from `.bin` files, convert them to `torch.float32` tensors to pass the images to kornia augmentation transforms, and we normalize image (images are scaled to [0,1]) after augmentation is applied. Instead, in this PR, we normalize image before applying kornia augmentation to remove redundancy.
> Fix Normalization order in data pipelines

- initial_config.yaml
- sleap_nn/data/custom_datasets.py
- sleap_nn/data/providers.py
- sleap_nn/training/get_bin_files.py
- sleap_nn/training/model_trainer.py
- tests/data/test_custom_datasets.py
- tests/inference/test_predictors.py
- tests/training/test_model_trainer.py
This is the first PR for #119. The torch `Dataset` modules for each model type is implemented. The user has the flexibility to choose   the data pipeline framework: LitData or vanilla torch `Dataset`s, which is passed as an argument while initializing `sleap_nn.training.model_trainer.ModelTrainer` class.
> Add torch Dataset classes

- sleap_nn/data/custom_datasets.py
- sleap_nn/training/model_trainer.py
- tests/data/test_custom_datasets.py
- tests/training/test_model_trainer.py
This PR adds an option to cache samples to disk as `.npz` files, apart from the in-memory caching available with torch Dataset pipeline in sleap-nn. These `.npz` files stores dictionaries with preprocessed images and keypoints extracted from the `.slp` file. In the `Dataset.__getitem__()` method, we apply augmentation, and generate confidence maps (and part affinity fields for bottom-up model) to ensure randomness. The `.npz` dir is then deleted at the end of training.
Example:
```py
from sleap_nn.training.model_trainer import ModelTrainer
trainer = ModelTrainer(config, data_pipeline_fw="torch_dataset_np_chunks", np_chunks_path="./")
trainer.train()
```
> Generate np chunks for caching

- sleap_nn/training/model_trainer.py
- sleap_nn/training/utils.py
This PR adds a logic to check the available memory before caching the samples in the dataset pipeline. If the available memory is not sufficient, we revert to the `.npz` caching method instead of in-memory caching.
> Check memory before caching

- sleap_nn/training/model_trainer.py
This PR removes the usage of `eval` while [loading pre-trained weights](https://github.com/talmolab/sleap-nn/blob/bc75aaff0109dbc5249e7faad18cb4b88b233192/sleap_nn/training/model_trainer.py#L682) for ConvNext and SwinT models. We instead use a dictionary to map the strings to the corresponding objects.
> Replace `eval` with an explicit mapping dictionary

- sleap_nn/inference/predictors.py
- sleap_nn/training/model_trainer.py
- tests/inference/test_predictors.py
This PR fixes the script to save the predictions as a `.slp` file.
> Save `.slp` file after inference

- initial_config.yaml
- sleap_nn/data/custom_datasets.py
- sleap_nn/training/model_trainer.py
- tests/training/test_model_trainer.py
- training_config.yaml
This PR saves a configuration file in the chunks directory at the time of chunk creation. This helps to we can skip loading the full .slp file when we reuse the chunks and instead load parameters directly from the saved config—significantly speeding up initialization and reducing memory usage.
Related Issue: #171
> Save config with chunks

- docs/config.md
- docs/config_bottomup.yaml
- initial_config.yaml
- sleap_nn/config/trainer_config.py
- sleap_nn/training/model_trainer.py
- tests/training/test_model_trainer.py
- training_config.yaml
This PR adds two new parameters to the `trainer_config`: `profiler` and `strategy` where `profiler` is used to specify different profilers for `lightning.Trainer`, and `strategy` specifies the training strategy to be used.
> Add profiler and strategy parameters

- sleap_nn/data/custom_datasets.py
- sleap_nn/training/model_trainer.py
Previously, get_rank() always returned 0 because torch.distributed wasn’t initialized at the time it was called. As a result, the npz cache was created independently in each distributed worker, despite conditioning on rank.
This PR introduces a new rank attribute, which is correctly retrieved from the initialized Trainer via `trainer.global_rank`. This ensures that cache generation and other rank-specific operations are performed only by the main (rank 0) process.
> Fix multi-gpu training

- sleap_nn/data/custom_datasets.py
- sleap_nn/training/model_trainer.py
This PR fixes a bug with the dataset pipeline, where caching to disk si repeated across the different processes created in different GPUs in a multi-gpu training setup. Here, we ensure that _fill_cache() method is called only when rank is 0 or None (when trainer hasn't been initialized yet).
> Ensure caching of images to disk in rank:0

- sleap_nn/data/custom_datasets.py
This PR fixes a bug in caching images to disk when we set `use_existing_imgs` to `True`.
> Fix bug in caching images to disk

- environment.yml
- environment_cpu.yml
- environment_mac.yml
- sleap_nn/data/custom_datasets.py
- sleap_nn/training/model_trainer.py
Previously, when num_workers > 0, the open video backends (e.g., HDF5 via h5py) caused multiprocessing to fail since h5py objects cannot be pickled. However, because we're using cached images (preloaded from the labels), the video backend is no longer needed during training. This PR explicitly closes these videos so that we can safely leverage multiprocessing for data loading without triggering serialization errors.
> Close videos before creating data loaders

- sleap_nn/architectures/convnext.py
- sleap_nn/architectures/swint.py
This PR fixes a bug in convnext and swint backbones, to compute the number of up blocks (decoder blocks) using the output stride instead of  a default value.
> Fix up block computation for swint and convnext

- docs/config.md
- sleap_nn/config/data_config.py
- sleap_nn/train.py
- sleap_nn/training/model_trainer.py
- tests/fixtures/datasets.py
- tests/test_train.py
- tests/training/test_model_trainer.py
This PR adds an option to generate the validation data from train labels if `data_config.val_labels_path` is `None`. The user can specify the fraction of training set to be considered for val dataset in `data_config.validation_fraction`.
> Add option to get validation data from train labels

- sleap_nn/inference/topdown.py
- tests/inference/test_predictors.py
- tests/inference/test_topdown.py
This PR fixes label saving during centroid inference when using ground-truth labels. The `FindInstancePeaksGroundtruth` class returns ground-truth instances based on predicted centroids, but there were bugs preventing these predictions from being saved to .slp files. This PR resolves those issues and ensures predictions can now be correctly saved.
> Save labels with centroid inference

- sleap_nn/data/providers.py
- sleap_nn/inference/predictors.py
- sleap_nn/predict.py
- sleap_nn/tracking/tracker.py
- sleap_nn/tracking/utils.py
- tests/data/test_providers.py
- tests/inference/test_predictors.py
- tests/test_predict.py
This PR adds option to accept a frame range, e.g., `--frames 10-100` in the CLI. This replaces the current `--videoreader_start_idx` and `--videoreader_end_idx` parameters, aligning with the frame range notation used in the SLEAP GUI. The frame range is converted to a list before passing to `sleap_nn.inference.predictors.run_inference()`.
> Add option to parse frame ranges for videos

- sleap_nn/data/providers.py
- sleap_nn/inference/predictors.py
- sleap_nn/predict.py
- tests/data/test_providers.py
This PR adds the following CLI flags to control which frames should be used for inference.
- `--only-labelled`: Run inference only on frames with user-labeled instances.
- `--only-suggested`: Run inference only on frames marked as suggestions (e.g., unlabeled targets).
> Add control flags to run inference on select LabeledFrames

- sleap_nn/data/providers.py
- sleap_nn/inference/predictors.py
- sleap_nn/predict.py
- sleap_nn/train.py
- tests/data/test_providers.py
- tests/inference/test_predictors.py
- tests/test_predict.py
- tests/tracking/candidates/test_fixed_window.py
- tests/tracking/candidates/test_local_queues.py
- tests/tracking/test_tracker.py
This PR adds the option to inference on specific video when the user provides a `.slp` file to run inference on.
- `--video-index`: Index of the video in the project file.
- `--video-dataset`: Name or path of the video dataset (e.g., video0/video).
> Add support to run inference on specific video in a .slp file

- sleap_nn/tracking/candidates/fixed_window.py
- sleap_nn/tracking/candidates/local_queues.py
- sleap_nn/tracking/tracker.py
- sleap_nn/tracking/utils.py
This PR addresses a few bugs in the tracking module:
Fixed window tracking: Only tracks that are active within the current window should be considered. Previously, all tracks created up to that point were used, which could lead to incorrect matches.
Local queues (per SLEAP tracking logic): When the `max_tracks` limit is reached, unmatched instances should be assigned track = None. These instances are excluded from the final labeled frame.
> Minor fixes to tracking

- sleap_nn/evaluation.py
This PR fixes a minor bug in evaluation module, where it compares the `dataset` attribute of `video` object. However, the `dataset` attribute only exists for `HDF5` backend and not for `MediaVideo`.  In this fix, we first check if `dataset` attribute exists and then compare the dataset.
> Fix bug in evaluation

- sleap_nn/train.py
- tests/test_train.py
Previously, after training, predictions were saved only for the full labels file in `train_labels_path` when `val_labels_path` wasn't provided. This PR updates the logic to save predictions from the training and validation (and test if `test_path` is provided) datasets individually.
> Save train, val, test predictions after training

- docs/config.md
- docs/config_bottomup.yaml
- docs/config_centroid.yaml
- docs/config_single_instance.yaml
- docs/config_topdown_centered_instance.yaml
- sleap_nn/config/trainer_config.py
- sleap_nn/train.py
- tests/assets/minimal_instance_bottomup/initial_config.yaml
- tests/assets/minimal_instance_bottomup/training_config.yaml
- tests/assets/minimal_instance_centered_instance/initial_config.yaml
- tests/assets/minimal_instance_centered_instance/training_config.yaml
- tests/assets/minimal_instance_centroid/initial_config.yaml
- tests/assets/minimal_instance_centroid/training_config.yaml
This PR fixes minor bugs related to handling ZMQ-specific parameters. Previously, these parameters were managed as a dictionary, but they have now been refactored into a dedicated attrs class for consistency with other nested config parameters. We also add a new parameter to allow specifying the controller polling timeout.
> Fix bugs with zmq config

- sleap_nn/training/callbacks.py
- sleap_nn/training/lightning_modules.py
- sleap_nn/training/model_trainer.py
- tests/training/test_model_trainer.py
This PR adds part-wise loss logging to the CSV and introduces a custom CSVLogger, replacing the default PyTorch Lightning implementation, which includes excessive and often unnecessary logging (step losses). The custom logger offers more flexibility in logging only the desired metrics, resulting in a cleaner CSV log.
> Log part-wise losses

- sleap_nn/tracking/candidates/fixed_window.py
- sleap_nn/tracking/candidates/local_queues.py
- sleap_nn/tracking/track_instance.py
- sleap_nn/tracking/tracker.py
- tests/tracking/test_tracker.py
This PR adds support for tracking user-labeled instances. Previously, the tracking pipeline only supported predicted instances. With this update, users can now run the tracking pipeline on manually labeled instances. If both user-labeled and predicted instances are present in a frame, the tracker will prioritize user-labeled instances.
> Enable tracking on user-labeled instances

- docs/config.md
- docs/config_bottomup_convnext.yaml
- docs/config_bottomup_unet.yaml
- docs/config_centroid_swint.yaml
- docs/config_centroid_unet.yaml
- docs/config_multi_class_bottomup_unet.yaml
- docs/config_single_instance_unet.yaml
- docs/config_topdown_centered_instance_unet.yaml
- docs/config_topdown_multi_class_centered_instance_unet.yaml
- sleap_nn/config/trainer_config.py
- sleap_nn/train.py
- sleap_nn/training/model_trainer.py
- tests/config/test_trainer_config.py
- tests/config/test_training_job_config.py
- tests/fixtures/datasets.py
- tests/training/test_model_trainer.py
This PR adds `keep_viz` parameter to the config which if set to `False` deletes the `viz` folder created once the training is complete.
> Add `keep-viz` parameter

- sleap_nn/training/model_trainer.py
This PR fixes an issue with wandb logging by ensuring that the provided wandb configuration is correctly passed to `wandb.init()` call.
Ask ChatGPT
> Fix wandb logging

- sleap_nn/architectures/convnext.py
- sleap_nn/architectures/encoder_decoder.py
- sleap_nn/architectures/model.py
- sleap_nn/architectures/swint.py
- sleap_nn/architectures/unet.py
- sleap_nn/data/custom_datasets.py
- sleap_nn/training/model_trainer.py
This PR fixes the following bugs:
- Fix data duplication in multi-GPU training: When using an infinite data loader with multiple GPUs, data was being unnecessarily replicated. This is now resolved by limiting the number of training steps based on the number of available devices.
- Improve filter computation: Use round() instead of int() when computing the number of filters to avoid unintended down-rounding.
- WandB initialization check: Prevent duplicate WandB runs by checking if a run is already initialized before calling wandb.init(). This is particularly useful for compatibility with sweep-based executions.
> Minor bug fixes in training pipeline

- docs/config.md
- docs/sample_configs/config_bottomup_convnext.yaml
- docs/sample_configs/config_bottomup_unet.yaml
- docs/sample_configs/config_centroid_swint.yaml
- docs/sample_configs/config_centroid_unet.yaml
- docs/sample_configs/config_multi_class_bottomup_unet.yaml
- docs/sample_configs/config_single_instance_unet.yaml
- docs/sample_configs/config_topdown_centered_instance_unet.yaml
- docs/sample_configs/config_topdown_multi_class_centered_instance_unet.yaml
- sleap_nn/config/model_config.py
- sleap_nn/train.py
- sleap_nn/training/lightning_modules.py
- tests/assets/model_ckpts/minimal_instance_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/training_config.yaml
- tests/config/test_model_config.py
- tests/config/test_training_job_config.py
- tests/fixtures/datasets.py
- tests/test_train.py
- tests/training/test_lightning_modules.py
Currently, the `model_config` includes a `pretrained_weights` parameter that is only relevant for the Swin Transformer and ConvNeXt architectures. This PR moves the `pretrained_weights` setting into the dedicated convnext and swint config sections. 
Relevant issue: [#154](https://github.com/talmolab/sleap-nn/issues/154).
> Move convnext/ swint pretrained weights

- sleap_nn/config/data_config.py
- sleap_nn/config/get_config.py
- sleap_nn/config/training_job_config.py
- sleap_nn/config/utils.py
- sleap_nn/train.py
- tests/config/test_model_config.py
- tests/config/test_training_job_config.py
- tests/training/test_model_trainer.py
This PR fixes two issues: 
1. Classes with `@oneof` decorator is not raising a `ValueError` when more than one attributes are set. When verifying and loading configs, OmegaConf does not instantiate the attrs classes because it only creates and updates a `DictConfig` schema. Therefore, the `@oneof` validations in the `__init__` for each class would never run. To fix this, I added `OmegaConf.to_object()` function to represent the config into a database backed by the attrs classes. 
2. Allow optional label paths in config. `train_labels_path` and `val_labels_path` would now accept `None` values.
> Fix `@oneof` Validation and Add Support for None for train_labels_path

- tests/test_predict.py
- tests/tracking/candidates/test_fixed_window.py
- tests/tracking/candidates/test_local_queues.py
- tests/tracking/test_tracker.py
- tests/training/test_model_trainer.py
This PR removes permanent file creations after running `pytest  tests`, preventing the cumulative directories in the repository directory.
> Remove Permanent File Creations After Testing Locally

- .github/workflows/build.yml
This PR updates the build workflow to have an option to publish the package to `testpypi`.
> Add build ci option to release to testpypi

- pyproject.toml
This PR adds testspypi index to `pyproject.toml` to enable publishing to testpypi with uv
> Add testpypi index to toml

- sleap_nn/train.py
- tests/test_train.py
Currently `sleap-nn-train` does not take commandline overrides because of a bug with how hydra handles overrides, this PR solves it.
> More robust help injection in CLI

- sleap_nn/training/lightning_modules.py
This PR removes the unused `turtle` module import
> Remove `back` import in lightning module

- pyproject.toml
- sleap_nn/architectures/unet.py
This PR fixes a bug in how filters are computed for the UNet backbone. Previously, the calculation differed slightly from SLEAP due to rounding errors, which caused a layer mismatch when running inference with legacy SLEAP model weights. This update aligns the filter computation with SLEAP’s implementation, ensuring compatibility with models trained in the tensorflow framework.
Related Issue: #309
> Fix compute filters in unet

- docs/config.md
- docs/sample_configs/config_bottomup_convnext.yaml
- docs/sample_configs/config_bottomup_unet.yaml
- docs/sample_configs/config_centroid_swint.yaml
- docs/sample_configs/config_centroid_unet.yaml
- docs/sample_configs/config_multi_class_bottomup_unet.yaml
- docs/sample_configs/config_single_instance_unet.yaml
- docs/sample_configs/config_topdown_centered_instance_unet.yaml
- docs/sample_configs/config_topdown_multi_class_centered_instance_unet.yaml
- docs/training.md
- sleap_nn/config/get_config.py
- sleap_nn/config/model_config.py
- sleap_nn/config/trainer_config.py
- sleap_nn/data/custom_datasets.py
- sleap_nn/train.py
- sleap_nn/training/model_trainer.py
- tests/assets/model_ckpts/minimal_instance_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/training_config.yaml
- tests/config/test_trainer_config.py
- tests/config/test_training_job_config.py
In this PR, we introduce the following changes:
- Update the default value of `trainer_config.trainer_devices`.
- Fix the default run name logic: it now uses the number of labeled frames (instead of the number of label objects).
> Minor bug fixes

- sleap_nn/evaluation.py
- tests/test_evaluation.py
Previously, `Evaluator.evaluate()` returned VOC metrics only using `OKS` as the matching score. This PR extends the evaluation to include both `OKS`- and `PCK`-based matches, and returns metrics for both in the VOC output.
> Add pck to voc metrics

- sleap_nn/data/custom_datasets.py
- sleap_nn/training/lightning_modules.py
- sleap_nn/training/model_trainer.py
This PR fixes the following bugs:
- `torch.load()` in `lightning_modules.py` failed when using "gpu" as the device for map location, it should use "cuda" / "mps" / "cpu". Related Issue: #321 
- Fixes a bug in computing the length of the dataloader. (If there's only one sample, the code failed to return 1)
- Resolved a compatibility issue where MediaVideo backends did not work with the threading model used for caching. (Removing the thread-based approach for now)
> Fix bugs in training pipeline

- docs/config.md
- docs/sample_configs/config_bottomup_convnext.yaml
- docs/sample_configs/config_bottomup_unet.yaml
- docs/sample_configs/config_centroid_swint.yaml
- docs/sample_configs/config_centroid_unet.yaml
- docs/sample_configs/config_multi_class_bottomup_unet.yaml
- docs/sample_configs/config_single_instance_unet.yaml
- docs/sample_configs/config_topdown_centered_instance_unet.yaml
- docs/sample_configs/config_topdown_multi_class_centered_instance_unet.yaml
- sleap_nn/config/get_config.py
- sleap_nn/config/trainer_config.py
- sleap_nn/train.py
- sleap_nn/training/model_trainer.py
- tests/assets/model_ckpts/minimal_instance_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/training_config.yaml
- tests/training/test_model_trainer.py
This PR updates the ZMQ arguments to use port numbers instead of full addresses.
> Change zmq address to port arguments

- .gitignore
- docs/config.md
- docs/sample_configs/config_bottomup_convnext.yaml
- docs/sample_configs/config_bottomup_unet.yaml
- docs/sample_configs/config_centroid_swint.yaml
- docs/sample_configs/config_centroid_unet.yaml
- docs/sample_configs/config_multi_class_bottomup_unet.yaml
- docs/sample_configs/config_single_instance_unet.yaml
- docs/sample_configs/config_topdown_centered_instance_unet.yaml
- docs/sample_configs/config_topdown_multi_class_centered_instance_unet.yaml
- docs/training.md
- sleap_nn/config/get_config.py
- sleap_nn/config/trainer_config.py
- sleap_nn/train.py
- sleap_nn/training/model_trainer.py
- tests/assets/model_ckpts/minimal_instance_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_centroid/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_bottomup/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/initial_config.yaml
- tests/assets/model_ckpts/minimal_instance_single_instance/training_config.yaml
- tests/config/test_trainer_config.py
This PR fixes seeding in the training pipeline. Previously, the seed parameter in the config was defined but never applied. We now explicitly set the seed when provided. In multi-GPU setups, if validation labels are missing, we default the seed to 42 during train/val splitting to ensure all workers use the same split.
> Fix seeding in training workflow

- sleap_nn/data/providers.py
- sleap_nn/inference/predictors.py
- tests/assets/model_ckpts/minimal_instance_centered_instance/training_config.yaml
- tests/assets/model_ckpts/minimal_instance_multiclass_centered_instance/training_config.yaml
This PR resolves an inference stalling issue. Previously, when users interrupted execution with Ctrl+C, the SIGINT signal was caught but the Python process continued hanging. With this fix, the process now exits cleanly when interrupted.
> Fix inference stalling

- sleap_nn/training/model_trainer.py
- sleap_nn/training/utils.py
This PR adds functionality to automatically select GPUs with the most available memory when the number of training devices specified by the user is less than the total GPUs available. In this case, we query the memory utilization of each GPU, sort them by free memory, and allocate the devices with the highest availability.
> Auto-select GPUs

- docs/sample_configs/config_centroid_swint.yaml
- docs/sample_configs/config_centroid_unet.yaml
- sleap_nn/config/trainer_config.py
- sleap_nn/inference/predictors.py
- sleap_nn/predict.py
- tests/config/test_trainer_config.py
- tests/test_predict.py
This PR adds an option to pass in `sio.Labels` and `sio.Video` object instead of `data_path` to the `run_inference` function.
> Add option to pass labels and video objects

- sleap_nn/legacy_models.py
This PR fixes the weight mapping for legacy top-down ID models. Previously, the legacy mapper didn’t account for linear layers and failed to transpose their weight shapes to match PyTorch’s convention. This update ensures that linear layer weights are correctly transposed and mapped from TensorFlow to PyTorch.
> Fix mapping for legacy topdown id models

- README.md
- docs/index.md
- docs/installation.md
Previously, `uv tool install sleap-nn[torch-cuda128]` didn't  install torch with cuda support on windows (Related issue: #307). CUDA libraries aren’t getting installed because PyPi doesn’t have access to `tool.uv.index` . When we run `uv tool install` (installing `sleap-nn` from PyPi), it defaults to pulling in the standard torch and torchvision and for windows the default wheels is CPU (linux - CUDA if cuda is available, mac - CPU). This happens because PyPi cannot see the custom indices we provide in [tool.uv.index](https://github.com/talmolab/sleap-nn/blob/99b80451f2af0758c2f944f7ebc0465b71b59c37/pyproject.toml#L108-L139) (the metadata is not published with the wheel), so it cannot resolve CUDA wheels. 
`uv tool install` works when `--extra-index-url` is provided to point to the …
> Modify uv installation docs for cuda support

- docs/config.md
- docs/sample_configs/config_bottomup_unet_large_rf.yaml
- docs/sample_configs/config_bottomup_unet_medium_rf.yaml
- docs/sample_configs/config_centroid_unet.yaml
- docs/sample_configs/config_single_instance_unet_large_rf.yaml
- docs/sample_configs/config_single_instance_unet_medium_rf.yaml
- docs/sample_configs/config_topdown_centered_instance_unet_large_rf.yaml
- docs/sample_configs/config_topdown_centered_instance_unet_medium_rf.yaml
- docs/sample_configs/config_topdown_multi_class_centered_instance_unet.yaml
- sleap_nn/config/data_config.py
- sleap_nn/config/get_config.py
- sleap_nn/config/trainer_config.py
- sleap_nn/data/custom_datasets.py
- sleap_nn/data/providers.py
- sleap_nn/train.py
- tests/config/test_trainer_config.py
- tests/data/test_custom_datasets.py
- tests/training/test_lightning_modules.py
This PR fixes a few minor issues with TopDown and BottomUp ID models. 
- The ID models dataset classes were re-computing the tracks from the labels file. However, they should just grab it from the head config `classes` parameter.
- Fix shape mismatch issue with BottomUp ID models
> Fix ID models
